--script para criacao da tabela de cliente
create table if not exists ibm.cliente (
        id integer generated by default as identity,
        cpf varchar(255) UNIQUE,
        email varchar(255),
        nome varchar(255),
        telefone varchar(255),
        data_cadastro date,
        primary key (id)
);


-- agencia
 create table if not exists ibm.agencia (
         codigo char(4)
 );

create table if not exists ibm.conta (
        id bigint generated by default as identity,
        ativa boolean not null,
        numero bigint AUTO_INCREMENT,
        cliente_id bigint not null,
        saldo decimal(19, 2) not null,
        primary key (id)
);

create table if not exists ibm.historico_transferencia (
        id integer generated by default as identity,
        data_hora_efetuada timestamp,
        data_hora_solicitada timestamp not null,
        realizada boolean not null,
        valor decimal(19, 2) not null,
        destino_id bigint not null,
        origem_id bigint not null,
        primary key (id)
);


-- Alter
alter table ibm.conta
add constraint FK_CONTA_CLIENTE_01 foreign key (cliente_id) references cliente;
alter table ibm.historico_transferencia
add constraint FK_HISTORICO_CONTA_01 foreign key (origem_id) references conta;
alter table ibm.historico_transferencia
add constraint FK_HISTORICO_CONTA_02 foreign key (destino_id) references conta;
